name: ci-setup

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test
      - name: Run lint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
      - name: Build the project
        run: npm run build